const projectList = [
  {
    title: "Wave",
    excerpt:
      "Wave is a electronic music blog, made as my first year Exam, with focus on accessability, performance and responsive design across most screen sizes. ",
    features:[' Search',' Sort by category',' Sort by date'], 
    type: "Project exam",
    img: "images/wave.jpg",
    id: 0,
    git: "https://github.com/Noroff-FEU-Assignments/project-exam-1-Jean-Christoffer",
    web: "https://charming-mousse-954d3d.netlify.app/",
    tools: [
      "images/css3.svg",
      "images/html5.svg",
      "images/wordpress.svg",
      "images/javascript.svg",
    ],
  },

  {
    title: "Museum",
    excerpt: "Museum is a fictional museum site, and was our first exam in HTML and CSS. It has a list of events and exhibitions.",
    features:[' Booking'], 
    type: "Semester project",
    img: "images/museum.jpg",
    id: 1,
    git: "https://github.com/Jean-Christoffer/Museum",
    web: "https://spectacular-sorbet-d98fe8.netlify.app/index.html",
    tools: ["images/css3.svg", "images/html5.svg", "images/javascript.svg"],
  },

  {
    title: "Gamehub",
    excerpt: "Gamehub was my first project that combined HTML,CSS and JS. I also experimented with some basic Three.js. ",
    features:[' Search',' Sort by category',' Add to cart', ' Checkout'], 
    type: "Cross course assigment",
    img: "images/gamehub.jpg",
    id: 2,
    git: "https://github.com/Jean-Christoffer/gamehubFinal",
    web: "https://gamehub-f-inal.vercel.app/",
    tools: [
      "images/css3.svg",
      "images/html5.svg",
      "images/wordpress.svg",
      "images/javascript.svg",
      "images/three.svg",
    ],
  },
  {
    title: "Portfolio",
    excerpt: "This is my final assignment of year one. The model is made with Ready player me, and animated with adobe mixamo and imported with React three fiber. The Iframe inside the laptop is a seperate page i made to fit inside the laptop. The shaders inside are made in Three.js",
    features:[' Animation',' 3D'], 
    type: "Course assigment",
    img: "images/port.jpg",
    id: 3,
    git: "https://github.com/Jean-Christoffer/portfolioMain",
    web: "https://portfolio-main-mauve.vercel.app/",
    tools: ["images/react.svg", "images/mui.svg", "images/three.svg"],
  },
  {
    title: "MovieBase",
    excerpt: "A site I made to practice React and to work with API's. ",
    features:[' Search',' Wishlist','Sort by category',' Sort by votes',' Sort by rating',' Sort by top 100'], 
    type: "Personal",
    img: "images/movie.jpg",
    id: 4,
    git: "https://github.com/Jean-Christoffer/Movie-base",
    web: "https://movie-base-mauve.vercel.app/",
    tools: ["images/react.svg", "images/mui.svg"],
  },
];
export default projectList